"""Smoke test for the universal MoE dispatch kernel.

Runs a tiny fused forward pass and checks output shapes and finiteness. Triton
JIT-compiles at runtime, so this needs a CUDA/ROCm GPU; it is skipped
automatically on CPU-only hosts (e.g. a laptop) and is meant to run on the
build/benchmark box.
"""
from pathlib import Path

import pytest
import torch

pytestmark = pytest.mark.skipif(
    not torch.cuda.is_available(), reason="Triton kernels require a GPU"
)

PROJECT_ROOT = Path(__file__).resolve().parent.parent


def _load_kernel():
    """Load the kernel the way a user would, falling back to the source tree.

    Once ``build/torch-universal`` has been generated by kernel-builder,
    ``get_local_kernel`` exercises the exact packaged layout. Before that, we
    import straight from ``torch-ext`` so the test is useful during development.
    """
    try:
        from kernels import get_local_kernel

        return get_local_kernel(PROJECT_ROOT, "moe_dispatch")
    except Exception:
        import sys

        sys.path.insert(0, str(PROJECT_ROOT / "torch-ext"))
        import moe_dispatch

        return moe_dispatch


def test_fused_moe_forward_shapes():
    torch.manual_seed(0)
    moe = _load_kernel()

    num_tokens, hidden, ffn, num_experts, top_k = 64, 256, 512, 8, 2
    dtype, dev = torch.float16, "cuda"

    hidden_states = torch.randn(num_tokens, hidden, dtype=dtype, device=dev)
    router_weight = torch.randn(num_experts, hidden, dtype=dtype, device=dev)
    w_gate = torch.randn(num_experts, ffn, hidden, dtype=dtype, device=dev) * 0.02
    w_up = torch.randn(num_experts, ffn, hidden, dtype=dtype, device=dev) * 0.02
    w_down = torch.randn(num_experts, hidden, ffn, dtype=dtype, device=dev) * 0.02

    out, idx, weights = moe.fused_moe_forward(
        hidden_states, router_weight, w_gate, w_up, w_down,
        num_experts=num_experts, top_k=top_k, gating="softmax",
    )

    assert out.shape == (num_tokens, hidden)
    assert idx.shape == (num_tokens, top_k)
    assert weights.shape == (num_tokens, top_k)
    assert torch.isfinite(out).all()
